# Generated by Django 5.2.6 on 2025-09-15 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_thread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Message',
            new_name='content',
        ),
    ]
